osx_image: xcode 11.3
language: swift
os: osx
xcode_project: TravisCIDemo.xcodeproj
xcode_scheme: TravisCIDemo
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X


script:
 - fastlane beta
    


