osx_image: xcode 11.3
language: swift
os: osx
xcode_project: TravisCIDemo.xcodeproj
xcode_scheme: TravisCIDemo
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

install:
 - sudo bundle install
 - sudo bundle update fastlane
before_script:
 - sudo gem install fastlane
 - sudo gem cleanup
script:
 - fastlane useMatch
    


