
setup_travis
opt_out_usage

default_platform :ios

lane :archive do |op|

  puts "请输入版本描述信息："
  desc = STDIN.gets

  version = op[:version]

  gym(
	 scheme: "TravisCIDemo",
	 export_method: "ad-hoc",
	 export_xcargs: "-allowProvisioningUpdates",
	 output_directory: "~/Desktop/outputAPI",
   configuration: "Debug",  #Release会生成dsym文件，而Debug不会
   output_name: version
  )

end

lane :beta do


  match(
type: "adhoc", 
keychain_password: "123456", 
app_identifier: "com.kwgproperty.HeJingBigMemberYiHe"
)

  gym(scheme: "TravisCIDemo",export_method: "ad-hoc")
end



