
default_platform :ios

lane :archive do |op|

  puts "请输入版本描述信息："
  desc = STDIN.gets

  version = op[:version]

  gym(
	 scheme: "TravisCIDemo",
	 export_method: "ad-hoc",
	 export_xcargs: "-allowProvisioningUpdates",
	 output_directory: "~/Desktop/outputAPI",
   configuration: "Debug",  #Release会生成dsym文件，而Debug不会
   output_name: version
  )

print <<`EOF`
    ls -al
EOF

  #build_app(export_method: "ad-hoc", export_xcargs: "-allowProvisioningUpdates", output_directory: "~/Desktop/outputAPI")
  
	
  # pgyer(
  #  api_key: "a215682d481d742271b61aabfe1baffe", 
  #  user_key: "06c794bc27fbe97b626a3a21f12419f5",
  #  password: "12345678", 
  #  update_description: "#{desc}"
  # )
end

lane :beta do
  match(type: "adhoc", readonly: is_ci,keychain_password: "123456", app_identifier: "com.kwgproperty.HeJingBigMemberYiHe")

  gym(scheme: "TravisCIDemo",export_method: "ad-hoc")
end



